### ISSUE TITLE
Reduce image size by using another base image

### ISSUE THREAD

**Issue by F21** [nerdammer/dockers#2]
Maybe the docker image can be reduced by using [alpine](https://registry.hub.docker.com/_/alpine/) or busybox as the base image.

**Comment by rodolphopivetta** [comment]
@F21, do you tried to use alpine as the base image?

**Comment by F21** [comment]
@rodolphopivetta I recently moved our [Boostport/hbase-phoenix-all-in-one](https://github.com/Boostport/hbase-phoenix-all-in-one) image from Ubuntu to [java:8-jre-alpine](https://hub.docker.com/_/java/) and it works pretty well. I haven't had a chance to use it in production, but the above image worked fine for our tests.

**Comment by rodolphopivetta** [comment]
thx, i'll take a look
